name: Publish to crates.io

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      # Optional: install a Rust toolchain.
      - uses: dtolnay/rust-toolchain@stable

      - name: Authenticate with crates.io (Trusted Publishing)
        id: auth
        uses: rust-lang/crates-io-auth-action@v1

      - name: Install shipper
        run: cargo install shipper-cli --locked

      # Restore shipper state from previous run (for resumability)
      - name: Restore shipper state
        uses: actions/download-artifact@v4
        with:
          name: shipper-state
          path: .shipper
        continue-on-error: true

      - name: Publish (resumable)
        run: shipper publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

      # Save shipper state for next run (even if publish fails)
      - name: Save shipper state
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: shipper-state
          path: .shipper
          retention-days: 1
